# Generated by Django 4.2 on 2023-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='quantity',
        ),
    ]
