# Generated by Django 4.2 on 2023-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
