# Generated by Django 4.2 on 2023-05-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
    ]
