# Generated by Django 4.2 on 2023-05-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cart_total_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
